server:
  port: 8080

spring:
  application:
    name: digimon-api
  datasource:
    url: jdbc:postgresql://localhost:5432/digi-mon
    username: postgres
    password: postgrespw
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: when-authorized
    info:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
